### ISSUE TITLE
tf variable does not exist e.g. sin_out/BiasAdd/_39

### ISSUE THREAD

**Issue by seivazi** [dougsm/mvp_grasp#14]
Running roslaunch mvp_grasping grasp_entropy_service.launch throw a tf error:

[ERROR] [1581599830.446864]: Error processing request: 2 root error(s) found.
  (0) Failed precondition: Error while reading resource variable pos_out/bias from Container: localhost. This could mean that the variable was uninitialized. Not found: Resource localhost/pos_out/bias/N10tensorflow3VarE does not exist.
	 [[{{node pos_out/BiasAdd/ReadVariableOp}}]]
	 [[sin_out/BiasAdd/_39]]
  (1) Failed precondition: Error while reading resource variable pos_out/bias from Container: localhost. This could mean that the variable was uninitialized. Not found: Resource localhost/pos_out/bias/N10tensorflow3VarE does not exist.
	 [[{{node pos_out/BiasAdd/ReadVariableOp}}]]
0 successful operations.
0 derived errors ignored.
['Traceback (most recent call last):\n', '  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 629, in _handle_request\n    response = convert_return_to_response(self.handler(request), self.response_class)\n', '  File "/home/seivazi/catkin_ws/src/mvp_grasp/mvp_grasping/ros_nodes/grasp_entropy_node.py", line 128, in update_service_handler\n    points, angle, width_img, _ = predict(depth_crop, process_depth=False, depth_nan_mask=depth_nan_mask)\n', '  File "/home/seivazi/catkin_ws/src/mvp_grasp/ggcnn/src/ggcnn/ggcnn.py", line 87, in predict\n    pred_out = model.predict(depth.reshape((1, 300, 300, 1)))\n', '  File "/home/seivazi/.local/lib/python2.7/site-packages/tensorflow/python/keras/engine/training.py", line 1078, in predict\n    callbacks=callbacks)\n', '  File "/home/seivazi/.local/lib/python2.7/site-packages/tensorflow/python/keras/engine/training_arrays.py", line 363, in model_iteration\n    batch_outs = f(ins_batch)\n', '  File "/home/seivazi/.local/lib/python2.7/site-packages/tensorflow/python/keras/backend.py", line 3292, in __call__\n    run_metadata=self.run_metadata)\n', '  File "/home/seivazi/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1458, in __call__\n    run_metadata_ptr)\n', 'FailedPreconditionError: 2 root error(s) found.\n  (0) Failed precondition: Error while reading resource variable pos_out/bias from Container: localhost. This could mean that the variable was uninitialized. Not found: Resource localhost/pos_out/bias/N10tensorflow3VarE does not exist.\n\t [[{{node pos_out/BiasAdd/ReadVariableOp}}]]\n\t [[sin_out/BiasAdd/_39]]\n  (1) Failed precondition: Error while reading resource variable pos_out/bias from Container: localhost. This could mean that the variable was uninitialized. Not found: Resource localhost/pos_out/bias/N10tensorflow3VarE does not exist.\n\t [[{{node pos_out/BiasAdd/ReadVariableOp}}]]\n0 successful operations.\n0 derived errors ignored.\n']

I printed the tf variables and for some reason node pos_out/BiasAdd/ReadVariableOp, sin_out/BiasAdd/_39 is missing. See below:

<tf.Variable 'conv2d_1/kernel:0' shape=(9, 9, 1, 32) dtype=float32>
<tf.Variable 'conv2d_1/bias:0' shape=(32,) dtype=float32>
<tf.Variable 'conv2d_2/kernel:0' shape=(5, 5, 32, 16) dtype=float32>
<tf.Variable 'conv2d_2/bias:0' shape=(16,) dtype=float32>
<tf.Variable 'conv2d_3/kernel:0' shape=(3, 3, 16, 8) dtype=float32>
<tf.Variable 'conv2d_3/bias:0' shape=(8,) dtype=float32>
<tf.Variable 'conv2d_transpose_1/kernel:0' shape=(3, 3, 8, 8) dtype=float32>
<tf.Variable 'conv2d_transpose_1/bias:0' shape=(8,) dtype=float32>
<tf.Variable 'conv2d_transpose_2/kernel:0' shape=(5, 5, 16, 8) dtype=float32>
<tf.Variable 'conv2d_transpose_2/bias:0' shape=(16,) dtype=float32>
<tf.Variable 'conv2d_transpose_3/kernel:0' shape=(9, 9, 32, 16) dtype=float32>
<tf.Variable 'conv2d_transpose_3/bias:0' shape=(32,) dtype=float32>
<tf.Variable 'pos_out/kernel:0' shape=(2, 2, 32, 1) dtype=float32>
<tf.Variable 'pos_out/bias:0' shape=(1,) dtype=float32>
<tf.Variable 'cos_out/kernel:0' shape=(2, 2, 32, 1) dtype=float32>
<tf.Variable 'cos_out/bias:0' shape=(1,) dtype=float32>
<tf.Variable 'sin_out/kernel:0' shape=(2, 2, 32, 1) dtype=float32>
<tf.Variable 'sin_out/bias:0' shape=(1,) dtype=float32>
<tf.Variable 'width_out/kernel:0' shape=(2, 2, 32, 1) dtype=float32>
<tf.Variable 'width_out/bias:0' shape=(1,) dtype=float32>
<tf.Variable 'RMSprop/iter:0' shape=() dtype=int64>
<tf.Variable 'RMSprop/decay:0' shape=() dtype=float32>
<tf.Variable 'RMSprop/learning_rate:0' shape=() dtype=float32>
<tf.Variable 'RMSprop/momentum:0' shape=() dtype=float32>
<tf.Variable 'RMSprop/rho:0' shape=() dtype=float32>
<tf.Variable 'RMSprop/conv2d_1/kernel/rms:0' shape=(9, 9, 1, 32) dtype=float32>
<tf.Variable 'RMSprop/conv2d_1/bias/rms:0' shape=(32,) dtype=float32>
<tf.Variable 'RMSprop/conv2d_2/kernel/rms:0' shape=(5, 5, 32, 16) dtype=float32>
<tf.Variable 'RMSprop/conv2d_2/bias/rms:0' shape=(16,) dtype=float32>
<tf.Variable 'RMSprop/conv2d_3/kernel/rms:0' shape=(3, 3, 16, 8) dtype=float32>
<tf.Variable 'RMSprop/conv2d_3/bias/rms:0' shape=(8,) dtype=float32>
<tf.Variable 'RMSprop/conv2d_transpose_1/kernel/rms:0' shape=(3, 3, 8, 8) dtype=float32>
<tf.Variable 'RMSprop/conv2d_transpose_1/bias/rms:0' shape=(8,) dtype=float32>
<tf.Variable 'RMSprop/conv2d_transpose_2/kernel/rms:0' shape=(5, 5, 16, 8) dtype=float32>
<tf.Variable 'RMSprop/conv2d_transpose_2/bias/rms:0' shape=(16,) dtype=float32>
<tf.Variable 'RMSprop/conv2d_transpose_3/kernel/rms:0' shape=(9, 9, 32, 16) dtype=float32>
<tf.Variable 'RMSprop/conv2d_transpose_3/bias/rms:0' shape=(32,) dtype=float32>
<tf.Variable 'RMSprop/pos_out/kernel/rms:0' shape=(2, 2, 32, 1) dtype=float32>
<tf.Variable 'RMSprop/pos_out/bias/rms:0' shape=(1,) dtype=float32>
<tf.Variable 'RMSprop/cos_out/kernel/rms:0' shape=(2, 2, 32, 1) dtype=float32>
<tf.Variable 'RMSprop/cos_out/bias/rms:0' shape=(1,) dtype=float32>
<tf.Variable 'RMSprop/sin_out/kernel/rms:0' shape=(2, 2, 32, 1) dtype=float32>
<tf.Variable 'RMSprop/sin_out/bias/rms:0' shape=(1,) dtype=float32>
<tf.Variable 'RMSprop/width_out/kernel/rms:0' shape=(2, 2, 32, 1) dtype=float32>
<tf.Variable 'RMSprop/width_out/bias/rms:0' shape=(1,) dtype=float32>

**Comment by dougsm** [comment]
Hello,
I just spent a little bit of time getting the ggcnn package up and running to test this out.  Just to make sure we're on the same codebase, I have pushed a couple of small changes which fix the session bugs you mentioned in another thread.
I have also pushed an updated realsense_wrist.launch file that works with the newest realsense2_camera package... annoying they seem to have a bunch of things, but it works now.
The code in the ggcnn package (i.e. both ggcnn_predict_rt.py and ggcnn_service.launch) as it is right now runs for me on Ubuntu 18.04, Ros Melodic, Python 2.7, tensorflow-gpu 1.14, cuda 10.1 and CuDNN 7.6.5
